[metadata]
name    = "tcp-transfer"


[global]
plan    = "testbed"
case    = "tcp-transfer"
builder = "docker:go"
runner  = "local:docker"

total_instances = 2

[[groups]]
id = "nodes"
instances = { count = 2 }

[groups.build]

[groups.run]
[groups.run.test_params]
input_data = "random"
file_size = "4000000000"
run_timeout_secs = "3000"
timeout_secs = "12000"
run_count = "1"
leech_count= "1"
passive_count = "0"
max_connection_rate = "100"
# input_data = "random"
# file_size = "10000000,30000000,50000000"
latency_ms= "0"
bandwidth_mb= "0"
enable_tcp= "false"
enable_dht= "false"
long_lasting = "true"